language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install http://files.openslides.org/Beta/openslides-1.4b2.tar.gz"
  - "pip install -r requirements.txt --use-mirrors"
script: "fab travis_ci"
